



install:
	INSTALL_PATH=""/Users/$$USER/"Application Support"/Pure""
	echo $$INSTALL_PATH
	# mkdir -p $$INSTALL_PATH
	# mv src/*.py $$INSTALL_PATH/*.py
	# cd $$INSTALL_PATH
	# chmod +x src/*.py
	# echo "export PATH=\$$PATH:\"$$INSTALL_PATH\"" >> ~/.bashrc
	
test: 
	python3 -m unittest -v tests/seedTests

run:
	@echo python3 $$SCRIPT